### ISSUE TITLE
get_spike_count, get_spike_train unimplemented.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#106]
In the file [https://github.com/scidash/neuronunit/blob/dev/neuronunit/capabilities/__init__.py#L50-L57](/dev/neuronunit/capabilities/__init__.py)

I think that definitions with a body that consists of: `raise NotImplementedError` are methods that are meant to be inherited inside child classes (ie raise NotImplementedError is a bit the same as `pass`.

I am at a stage at the moment where I am able to pass a model around between CPUs. I have implemented `get_spike_train`, and `get_spike_count` in backend NEURON however the version of model that is passed to other CPUs is missing these class attributes/methods.

```
class ProducesSpikes(sciunit.Capability):
    """Indicates that the model produces spikes.
    No duration is required for these spikes.
    """

    def get_spike_train(self):
        """Gets computed spike times from the model.
        Arguments: None.
        Returns: a neo.core.SpikeTrain object.
        """

        raise NotImplementedError()

    def get_spike_count(self):
        spike_train = self.get_spike_train()
        return len(spike_train)


class ProducesActionPotentials(ProducesSpikes, 
                               ProducesMembranePotential):
    """Indicates the model produces action potential waveforms.
    Waveforms must have a temporal extent.
    """

    def get_APs(self):
        """Gets action potential waveform chunks from the model.
        Returns
        -------
        Must return a neo.core.AnalogSignal.
        Each column of the AnalogSignal should be a spike waveform.
        """

        raise NotImplementedError()

    def get_AP_widths(self):
        action_potentials = self.get_APs()
        widths = spikes2widths(action_potentials)
        return widths
```

**Comment by rgerkin** [comment]
`Capabilities` are meant to be implemented at the level of the `Model`, with the backend handling some of the backend-specific functions they may call.  For example, `ReducedModel` implements `get_membrane_potential` by calling `run` and then checking for information about membrane potential in the attributes of the model instance that `run` has hopefully added.  `run` is implemented by the parent class `LEMSModel` which calls `local_run` and uses the returned values to update the instance attributes as expected by `run`.  `local_run` is in turn implemented by each backend, returning a dictionary of results.  

The higher level methods like `get_spike_count` are not expected to have a backend-specific implementation.  Once a membrane potential is in hand, computing things like the number of spikes should be independent of the backend.  Consequently, the implementation of things like `get_spike_count` is in the `Capability` itself, implemented as a call to `get_spike_train` followed by counting its size.  `get_spike_train` is in turn implemented by the `Model` (in this case, `ReducedModel`) which mostly just uses the reference implementation found in `capabilities/spike_functions`.  

So the call stack for `get_spike_count` is, with the location of its implementation in parentheses:  
`get_spike_count` (in the ProducesSpikes Capability definition)
`get_spike_train` (in the ReducedModel definition)
`get_membrane_potential` (in the ReducedModel definition)
`run` (in the LEMSModel definition)
`local_run` (in the definition for each Backend)

@russelljjarvis 
`NotImplementedError` implies that one of the methods that was described in the Capability definition but was left with no implementation (i.e. with only `raise NotImplementedError`) was not defined in the Model that claims that Capability.  It raise that error because there is no alternative: the test has resulted in a certain method being called and that method has no implementation and so cannot return the requested data.  

If you are experiencing this error on the other CPUs then something about my implementation of pickling and unpickling must be causing the original model itself to become unbound from the Capability `ProducesSpikes` so that methods like `get_spike_count` that are not expected to appear anywhere else no longer exist.  You should be able to verify by checking the list of parent classes, e.g. `print(self.__class__.__bases__)` that ProducesSpikes is missing on the other CPUs (but should still be there at the beginning on the first CPU when the test begins).  

This error is sort of consistent with another that I have been seeing and I will be looking into this today.

**Comment by rgerkin** [comment]
This is probably either fixed or obsolete with the new Backend implementation.
