### ISSUE TITLE
Old travis/docker file.

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#126]
It would be cool if I could run my new non-core unit_test, tests using Travis-cl but by using a docker container that will go a bit further than anaconda, in enabling `ipyparallel` etc.

I think scidash/neuronunit used to have a good travis file (that I could use as a template), that pulled from docker-stacks, but I can't find it. I wonder if it might be in scidash/assets or something?

**Comment by rgerkin** [comment]
Take a look [here](https://github.com/scidash/neuronunit/commit/ac265370fe6https://github.com/scidash/neuronunit/commit/ac265370fe672ab7105f5dad1bc2cf6d62a31c06?diff=split72ab7105f5dad1bc2cf6d62a31c06?diff=split).  The left side is what the Travis file looked like when we were relying on Docker, so you can use something like that as a template.  

I propose that you create a new branch that contains a travis file like this, and then whenever you want to run deep tests, you can pull changes from the other branches into it and that will trigger it to run.  But otherwise when we are working on those other branches it won't run and so we won't have to worry about it.

**Comment by russelljjarvis** [comment]
AOK. The link to the diffing was broken (it's probably only visible from your login to GH) but I think I found a helpful enough version by splitting the link in half, which reveals the commit where the development switched away from annonda.

https://github.com/scidash/neuronunit/commit/ac265370fe672ab7105f5dad1bc2cf6d62a31c06?diff=split72ab7105f5dad1bc2cf6d62a31c06?diff=split

**Comment by rgerkin** [comment]
See also scidash/docker-stacks#24 for another idea.  Basically, you create a Docker container with all the stuff you need, and when it is built, you push it to Docker Hub/Cloud, and Travis tests it with a simple script.
