### ISSUE TITLE
NEURON backend models, should have an optional keyword DTC object argument in the constructor

### ISSUE THREAD

**Issue by russelljjarvis** [scidash/neuronunit#138]
This might neaten up DTC-> neuronunit model update steps, and it could also provide a means to store `current_source_name`, and `cell_name` in DTCs and have them update models each time a new model object gets minted, with the advantage that a disk/file read could then be replaced with a memory read.

**Comment by rgerkin** [comment]
As it stands the `backend=` kwarg of the model doesn't just have to be a string like "NEURON", it can be a tuple (see [here](https://github.com/scidash/neuronunit/blob/master/neuronunit/models/__init__.py#L52)).  In that tuple, the first item should be the name (e.g. "NEURON") and then subsequent items can be args (as a list) and kwargs as a dict.   

So, for example:  
`backend = ("NEURON",[1,2,3],{'a':11,'b':22})`
Will then invoke the init_backend for the NEURONBackend (see [here](https://github.com/scidash/neuronunit/blob/master/neuronunit/models/__init__.py#L81) with:  
`init_backend(1,2,3,a=11,b=22)` rather than the vanilla `init_backend()` we usually call.  

So all you have to do is set NEURON's init_backend to take an optional DTC kwargs, e.g. change [this](https://github.com/scidash/neuronunit/blob/master/neuronunit/models/backends.py#L200) to something like `def init_backend(self, DTC=None):` and then you can check for `DTC is not None` and use it to set the various things provided by the DTC.  Then all this should be called when you instantiate the model with `model = ReducedModel('/path/to/model', backend=('NEURON', {'DTC':dtc}))` where `dtc` is some DTC instance.

**Comment by rgerkin** [comment]
If you write a simple unittest for this (which fails, presumably), I can take a look at it and see why it fails.

**Comment by rgerkin** [comment]
@russelljjarvis Does this work for you now?

**Comment by rgerkin** [comment]
Please make a formula reproducing this problem.

**Comment by russelljjarvis** [comment]
I think the problem is in the constructor. In the file:

models/backends/neuron.py
lines 16 - 53:

The condition:        
`if type(DTC) is not None: ` never executes. It's not about the syntax of this condition. For instance, using very explicit `if type(DTC) is not type(None): also wouldn't work.  Or `if not isinstance(DTC,None)` equally would not work.

I think the problem is instead here:

`model = ReducedModel(get_neab.LEMS_MODEL_PATH,name=str('vanilla'),backend=('NEURON',{'DTC':dtc}))`

Particularily in the way backend is assigned a tuple that contains a string as the first element, and a dictionary as the second element. I don't think this information is being handled properly in the constructor code, corresponding to this method signature.


```
    def init_backend(self, attrs = None, cell_name = None, current_src_name = None, DTC = None):
        '''Initialize the NEURON backend for neuronunit.
        Optional Key Word Arguments:
        Arguments: attrs a dictionary of items used to update NEURON model attributes.
        cell_name, and _current_src_name should not attain arbitrary values, rather these variable names
        may need to have consistency with an underlying jNEUROML model files:
        LEMS_2007One_nrn.py  LEMS_2007One.xml
        cell_name: A string that represents the cell models name in the NEURON HOC space.
        current_src_name: A string that represents the current source models name in the NEURON HOC space.
        DTC: An object of type Data Transport Container. The data transport container contains a dictionary of model attributes
        When the DTC object is provided, it\'s attribute dictionary can be used to update the NEURONBackends model attribute dictionary.
        '''
        if not NEURON_SUPPORT:
            raise BackendException("The neuron module was not successfully imported")


        self.neuron = None
        self.model_path = None
        self.h = h
        # Should check if a legitimately parallel MPI based NEURON is supported.
        self.lookup = {}

        super(NEURONBackend,self).init_backend()
        self.model.unpicklable += ['h','ns','_backend']
        if cell_name:
            self._cell_name = cell_name
        if current_src_name:
            self._current_src_name = current_src_name
        #if not isinstance(DTC, type(None)):
        if type(DTC) is not None:
            print('type \n\n\n\n\n\n', type(DTC), DTC)
            print(dir())

            assert 1==2
            print('never gets here \n\n\n\n\n\n')
            print(DTC.attrs, 'the dtc attrs empty?')
            self.model.set_attrs(DTC.attrs)
```

**Comment by rgerkin** [comment]
We agreed that this is solved.
