### ISSUE TITLE
AP width computation issue

### ISSUE THREAD

**Issue by JustasB** [scidash/neuronunit#18]
Currently, the AP half-width is computed by taking a 10ms window around an AP and:

1. Finding the maximum membrane v
2. The [minimum](https://github.com/scidash/neuronunit/blob/dbee6e6c91813af5766a6bd83e932bda0bd91d1a/neuronunit/capabilities/spike_functions.py#L83) v
3. Counting the samples where v is above mean(min,max)

Should #2 be using the v of the AP threshold? According to [NE definition](http://neuroelectro.org/ephys_prop/ontology/): 

> Calculated as the AP duration at the membrane voltage halfway between **AP threshold** and AP peak. Most commonly calculated using first AP in train at rheobase. current.

**Comment by rgerkin** [comment]
Yes, I think this is a shortcut on my part because at the time the AP threshold values in Neuroelectro were unreliable and using the minimum instead of the threshold didn't make a huge difference, so I was willing to introduce a small bit of systematic error to exclude a large amount of random error.  

I think the threshold measurements are reliable enough that they can be used now.  Also, there is an APThreshold test so the code for computing the threshold can just be re-used.

**Comment by rgerkin** [comment]
@JustasB Fixed with 006143e.
