### ISSUE TITLE
Neuronunit Tests Dockerfile -> Showcase

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#52]
@russelljjarvis 
I would like to move/copy the contents of the `scidash/neuronunit/tests/Dockerfile` to `scidash/docker-stacks/neuronunit-showcase`.  The ideas is that `neuronunit-showcase` will be an environment that can run all the richer features of `neuronunit`.  Eventually these can be considered "core" features (after some more thorough testing).

**Comment by russelljjarvis** [comment]
Great, yes I am all for it of course. I need to start working on the abstract and seminar presentation about this work. So I think my emphasis will need to change to plotting some of the outputs temporarily.

But I still think I should try to get all of this to run on the NSG using the Singularity. For the nsga.py file it actually has nested parallelism (and thus better CPU utility), I believe that this could better fully taken advantage of when using more than 8 CPUs.

**Comment by russelljjarvis** [comment]
I want to be able to get both `exhaustive_search.py` and `nsga.py`

To return the actual score_matrix pandas data type (instead of the floats I gleaned out of it). This is because I want to be able to use the plot_function in bind score, or to be able to use matplotlib to plot related data (as it would be nice to actually see the Vm's that are output from these optimizations.

I have destroyed some of the HOC objects that are being stored inside the neuronunit testsuite object, but I think I need to actually destroy the models too, or just to replace them with my virtual model class.

```
    def get_membrane_potential(self):
        """
        Must return a neo.core.AnalogSignal.
        And must destroy the hoc vectors that comprise it.
        """
        import copy

        if self.h.cvode.active() == 0:
            fixedSignal = self.vVector.to_python()
            dt = self.h.dt
            dt_py=float(copy.copy(self.h.dt))
            fixedSignalcp=copy.copy(fixedSignal)
        else:
            fixedSignal = self.get_variable_step_analog_signal()
            fixedSignalcp=copy.copy(fixedSignal)
            dt = self.fixedTimeStep
            dt_py=float(copy.copy(self.fixedTimeStep))


        fidxedSignal=None
        self.h.dt=None
        self.fixedTimeStep=None
        return AnalogSignal( \
                 fixedSignalcp, \
                 units = mV, \
                 sampling_period = dt_py * ms \
        )
```

**Comment by rgerkin** [comment]
Done.
