### ISSUE TITLE
Should we switch from Scoop to IPyParallel?

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#80]
@russelljjarvis

**Comment by russelljjarvis** [comment]
# Arguments in favor of scoop:

* Already in use

* was designed for use with DEAP, and has tight DEAP integration in code conventions.

* Uses zeromq (Z0Q) natively which is more communication speed efficient than MPI

* Allows recursive calling of `futures.map` facilitating a tree shaped cluster topology that should result in a bigger spreading of code onto CPUs (greater utilization of parallel resources).

* Note I don't necessarily know that ipython lacks this feature.

# Scoop draw backs:
 *ipython unfriendly invocation patterns, limited documentation.

* verbose and unsugared syntax, causes obfuscation to casual code readers.

# ipython-parallel advantages. 

* great ongoing documentation and development. 

* full of syntactic sugar.

* should speed up development, and debugging.

# ipython-parallel  dis-advantages. 

* I don't yet understand its ipypthon parallels error messages.

* Even if it works, it seems a bit greedy and stupidly complex, to have an interactive notebook, that executes a now parallel python kernel inside json and html webpages. I can't imagine that the outcome would be bleedingly fast as an end product, but yet this approach should lead to faster and development and debugging. Perhaps there might be ways of speeding up the end product, such as converting notebooks back to regular ipython code, and then interpretating ipython to cython as much as possible.

* Seems to prefer that the ipcontoller, and the ip engines (exist in two seperate docker containers that are launched in parallel and communicate to each other via ssh tunneling, as several authors have noted .. Although I don't know the reasons for this preference, and if it really has to be so.

https://github.com/0x0L/jupyter-cluster
https://github.com/ActivisionGameScience/ipyparallel-mesos/
https://github.com/ipython/ipyparallel/issues/51

* Given the above point, that it prefers two separate dedicated docker containers that are run simultansuosly and communicate with each other: 

** It seems like the resulting nb, should not be user friendly to run, and would therefore be in violation of notebook philosophy.

** Mapping docker container to singularity image would be clumsy, since the singularity image would need a docker daemon, and two containers to execute. From experience, I know that docker in singularity is highly discorouged and not very good ... although this could change quickly?


* 0MQ as a communicator is not default, but can be enabled with a flag

**Comment by russelljjarvis** [comment]
After doing a lot of the work associated with switching, I now believe that the answer is yes, we should switch.

The two main reasons are: Better integration with documentation via, notebooking, and also because notebooks have checkpointing, which can save time on big runs.

I am getting the sense that ipyparallel might be slower than scoop, however I am unsure if things have to be this way, and if its possible to 

I also do not know exactly how to get read the stack traces off workers that fail. I am guessing you can set a flag that creates a verbose log file with each run but I am unsure how yet.

If stderr suddenly becomes accessible, then at least development (including documentation development time) might become faster via ipyparallel, at least because of checkpointing.

**Comment by rgerkin** [comment]
Sounds good.

**Comment by russelljjarvis** [comment]
Actually ipyparallel supports integration with dask, and dask as a backend. 

Dask has more mature documentation, in the sense that it is very realistic about performance improvements, and concerned that the code will not result in good enough utilization and efficiency of CPUs

https://gist.github.com/mrocklin/dc7fd426a6e405fef275

https://gist.github.com/mrocklin/dc7fd426a6e405fef275

dask also better support for hdf5 and pandas, but possibly less syntactic sugar. 

```
from ipyparallel import Client
c = Client()  # connect to IPyParallel cluster
e = c.become_dask()  # start dask on top of IPyParallel
```

Since ipythonparallel seems to be dask aware, hopefully, some of dasks features will converge into ipyparallel.

**Comment by russelljjarvis** [comment]
A pure dask implementation might allow for nested calls to map_reduce.

Also python-intel distributed has since been released, but it comes in binaries only, so it is not really open source I guess.
https://software.intel.com/en-us/distribution-for-python/features

**Comment by russelljjarvis** [comment]
I actually think we should switch to dask sometime in the future. This is based on what the primary author of ipyparallel recommends on stackexchange.

Dask is just as ipython friendly as ipyparallel, however I think it's also a more versatile tool, with more extensive documentation.

https://stackoverflow.com/questions/37998484/how-to-efficiently-chain-ipyparallel-tasks-and-pass-intermediate-results-to-engi

Option 2: dask.distributed

Full disclosure: I'm the primary author of IPython Parallel, about to suggest that you use a different tool.

It is possible to pass results from one task to another via engine namespaces and DAG dependencies in IPython parallel, but honestly, if your workflow looks like this, you should consider using dask distributed, which is designed specifically for this kind of computation graph. If you are already comfortable and familiar with IPython parallel, getting started with dask should not be too much of a burden.

**Comment by rgerkin** [comment]
I'm fine with it, but let's delay it until after the next release of NeuronUnit.  We really need to focus on code coverage, passing tests, and readable, documented code.  If IPyParallel passes simple tests but fails with very large optimizations, that is OK for the next release.

**Comment by russelljjarvis** [comment]
I agree delaying the implementation but planning to switch is a good choice.

**Comment by HamiltonWang** [comment]
> I accidentally switched first.
> 
> Reasons:
> 
> * Dask has great support for pandas/numpy. See here:

May I have an example for your implementation? I tried but I got some error

**Comment by russelljjarvis** [comment]
@HamiltonWang.

If you cast a numpy array to type 
```
pop_bag = dask.db.from_sequence(pop)
```
you can use:
```
pop=list(pop_bag.map(method_type).compute())
```
