### ISSUE TITLE
Can we get rid of VirtualModel?

### ISSUE THREAD

**Issue by rgerkin** [scidash/neuronunit#90]
VirtualModel seems like a hack that we should try to improve upon if we can.  Can you make a version of the optimization notebook that tries not to use VirtualModel, fails on whatever error that results, and then I can work on it from there?

**Comment by russelljjarvis** [comment]
Yes, I agree I will try to do this.

**Comment by rgerkin** [comment]
I think now that we can pickle and unpickle across processes in ipyparallel, we should be able to get rid of VirtualModel.

**Comment by russelljjarvis** [comment]
Although model can be pickled and unpickled when it passed around between the hub and the clients, this happens at an expense. Every time [h,ns,_backends] are removed from the core of the NEURONbackend object, for the model to be any good model parameters need to be redefined in `hoc` each time the model is transported. Additionally the HOC membrane and time recording vectors need to be redefined. 

The upshot of all of this, is that a lot of the virtual models functionality, will have to be effectively moved into NEURONbackend, such that model.parameters are reset, based on the picklable/retainable LEMS_model_params each time the model is transported. Additionally get_membrane potential would have to be implemented slightly differently again such that its input parameters are not HOC recording vectors, but rather are python lists instead. 

Probably inside the inject_square_current method, the HOC vectors need to be converted to python lists, such that the they persist after transport.

**Comment by russelljjarvis** [comment]
I think we now agree, that the architectural model involving a container (like VM) that ships model_parameters and other attributes between CPUs should be retained, but the name of the container should be changed to DataTransportContainer in order to avoid confusion.

The diagram below illustrates the current program architecture.

https://www.draw.io/#Hrusselljjarvis%2Finformatics_poster%2Fmaster%2Fbulletin_board.xml
